# osprey configuration file.

estimator:
    pickle: ff_bb_ang.pickl

strategy:
  name: gp
  params:
    seeds: 20
    kernels:
      - { name : GPy.kern.Matern52, params : {ARD : True}, options : {independent : False} }
    acquisition: { name : ei, params : {}}

search_space:
  tica__lag_time:
    min: 1
    max: 999
    type: int

  tica__n_components:
    min: 1
    max: 10
    type: int

  cluster__n_clusters:
    min: 10
    max: 1000
    type: int

cv:
    name: shufflesplit
    params:
      n_splits: 5
      test_size: 0.5

dataset_loader:
  # specification of the dataset on which to train the models.
  name: mdtraj
  params:
    trajectories: ~/msmbuilder_data/fs_peptide/trajectory-*.xtc
    topology: ~/msmbuilder_data/fs_peptide/fs-peptide.pdb
    stride: 10


trials:
  uri: sqlite:///osprey-trails.db
  project_name: ff_bb_ang
